//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sms.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Message
    {
        public int Id { get; set; }
        public byte[] ChangeCtr { get; set; }
        public System.Guid MessageId { get; set; }
        public string ReceiverPhone { get; set; }
        public string Sms { get; set; }
        public Nullable<System.DateTime> VerificationTime { get; set; }
        public string Status { get; set; }
    }
}
